services:
   redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379' 
   web:
        build: .
        ports:
            - "8000:5001"
        volumes:
            - .:/app
        depends_on:
            - redis
